name: 'repo-monitor'
author: 'ToyB0x'
description: 'Analyze repository metrics'
branding:
  color: 'blue'
  icon: 'activity'
inputs:
  GITHUB_TOKEN:
    description: "for PR comments and managing artifacts"
    required: true
  PR_NUMBER:
    description: "The pull request number to analyze"
    required: false
    default: ${{ github.event.number }}
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
    PR_NUMBER: ${{ inputs.PR_NUMBER }}
