name: 'Repo Performance'
author: 'ToyB0x'
description: 'Analyze repository metrics'
branding:
  color: 'blue'
  icon: 'activity'
runs:
  using: "composite"
  steps:
    - name: Build all packages
      run: npx @ts-bench/cli@latest
      shell: bash
      env:
        DB_FILE_NAME: "file:repo.sqlite"
