name: marketplace
on:
  pull_request:

permissions:
  contents: read # for checkout repository
  pull-requests: write # for creating/updating PR comments

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup & Restore Node cache
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version-file: 'package.json'

      - name: Install all packages
        run: pnpm install --frozen-lockfile

      - name: Build (include dts generation)
        run: pnpm build

      - id: analyze
        uses: './' # Uses an action in the root directory

      - name: Create PR comment
        working-directory: apps/cli
        run: gh pr comment ${{ github.event.number }} --body-file ${{ github.workspace }}/report.md --edit-last --create-if-none # upsert the last comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
