name: monitor
on:
  pull_request:

permissions:
  contents: read # for checkout repository
  pull-requests: write # for creating/updating PR comments

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup & Restore Node cache
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version-file: 'package.json'

      - name: Install all packages
        run: pnpm install --frozen-lockfile

      - name: Restore turbo cache
        uses: actions/cache@v4
        with:
          path: .turbo/cache
          key:
            turbo/${{ github.job }}/${{ github.ref_name }}/${{ github.sha }}
          restore-keys: |
            turbo/${{ github.job }}/${{ github.ref_name }}/
            turbo/${{ github.job }}/

      - name: Build (include dts generation)
        run: pnpm build

      - name: Migrate
        working-directory: packages/database
        run: pnpm db:migrate:deploy

      - name: Analyze
        working-directory: apps/cli
        run: node . analyze > report.txt

      - name: Create PR comment
        working-directory: apps/cli
        run: gh pr comment ${{ github.event.number }} --body-file report.txt --edit-last --create-if-none # upsert the last comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
